Django_PJT1/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('test/', views.test, name='test'),
    path('checked/', views.checked, name='checked'),

    path('user_page/<int:user_id>/', views.user_page, name='user_page'),
    path('user_page/<int:user_id>/edit/', views.edit_user_page, name='edit_user_page'),

    path('user_page/<int:user_id>/edit_image/', views.edit_user_image, name='edit_user_image'),
    path('user_page/<int:page_master_id>/damgle/create/', views.create_damgle, name='create_damgle'),
    path('user_page/<int:page_master_id>/damgle/<int:damgle_id>/delete', views.delete_damgle, name='delete_damgle'),
]

Django_PJT1/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('search_movie/', views.search_movie, name='search_movie'),
    path('<int:movie_id>/like/', views.toggle_like, name='like'),
    path('<int:movie_id>/reviews/create/', views.create_review, name='create_review'),
    # path('<int:movie_id>/reviews/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('<int:movie_id>/reviews/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

Django_PJT1/test_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
import movies
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', movies.views.index),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_PJT1/accounts/models.py
from django.db import models
from django.urls import reverse

# User < AbstractUser < AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.conf import settings


from django_extensions.db.models import TimeStampedModel
from movies.models import Genre

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class User(AbstractUser):
    nickname = models.CharField(max_length=30)
    like_genres = models.ManyToManyField(Genre, related_name='like_users')
    introduction = models.TextField()

class Image(models.Model):
    # Image.objects.get(id=1).user
    # User.objects.get(id=1).image_set.file.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    file = ProcessedImageField(
        processors=[ResizeToFill(600, 600)],
        upload_to = 'user_image/images/',
        format='JPEG',
        options={'quality': 90},
    )

class Damgle(models.Model):
    page_master = models.ForeignKey(User, on_delete=models.CASCADE, related_name='page_master')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)

    class Meta:
        ordering = ('id', )

Django_PJT1/movies/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
# User = get_user_model()
User = settings.AUTH_USER_MODEL

class Genre(models.Model):
    name = models.CharField(max_length=20)
    
class Movie(models.Model):
    MovieCd = models.IntegerField()
    movieName = models.CharField(max_length=30)
    movieNameE = models.CharField(max_length=30)
    pubDate = models.IntegerField()
    runtime = models.CharField(max_length=200)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='movie_genre') # 여기가 변경사항
    director = models.CharField(max_length=200)
    userRating = models.FloatField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    like_users = models.ManyToManyField(User, related_name='like_movies')
    
class Review(models.Model):
    content = models.CharField(max_length=150)
    score = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

Django_PJT1/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from accounts.models import Image, Damgle
User = get_user_model()

from django import forms
# from .models import Damgle


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'nickname', 'introduction',)

class CustomAuthenticationForm(AuthenticationForm):

    class Meta:
        model = User

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('file', )
        widgets = {
            'file': forms.FileInput(attrs={'multiple': True})
        }

class DamgleForm(forms.ModelForm):
    class Meta:
        model = Damgle
        fields = ('content',)

Django_PJT1/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from .forms import CustomAuthenticationForm, CustomUserCreationForm, DamgleForm
from .forms import CustomAuthenticationForm, CustomUserCreationForm, ImageForm, DamgleForm
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import get_user_model
from movies.models import Movie, Genre
from .models import Damgle
# import random
from accounts.models import Image
from django.db.models import Max
# from accounts.models import Damgle
User = get_user_model()

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_list')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            movies = Movie.objects.all()[:90]
            return render(request, 'accounts/choice.html', {
                'movies':movies
            })

    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/user_form.html', {
        'form':form
    })

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_list')
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:movie_list')

    else:
        form = CustomAuthenticationForm()
    return render(request, 'accounts/user_form.html', {
        'form':form,
    })

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

@login_required
@require_http_methods(['GET'])
def user_page(request, user_id):
    user = get_object_or_404(User, id = user_id)
    # image = //
    damgle_form = DamgleForm()
    # damgle_form.page_master_id = user.id
    damgles = Damgle.objects.filter(page_master_id = user_id)
    return render(request, 'accounts/user_page.html', {
        'user_info' : user,
        'damgle_form' : damgle_form,
        'damgles' : damgles,
    })
    # return render(request, 'accounts/user_page.html', {
    #     'user_info' : user,
    #     
    # })

@login_required
@require_http_methods(['GET', 'POST'])
def edit_user_page(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == "POST":
        # form = ArticleModelForm(request.POST) 이렇게 쓰면 새종이에 데이터 쓰는 것이고 instance=article 하면 있는 데이터에 덮어써서 수정하는 것
        form = CustomUserCreationForm(request.POST, instance=user) # 사용자가 '새로 입력한 데이터'를 미리 만들어둔 case에 넣음
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('accounts:user_page', user_id)
    # 사용자가 수정하기 위한 html 파일을 요청함/ 있던 데이터를 찾아서 html에 넣어서 보내줌
    else:        
        form = CustomUserCreationForm(instance=user)
    # 위와 겹치므로 한칸 앞으로 가서 코드 간단히 해줌
    return render(request, 'accounts/user_form.html', {
        'form':form,
    })
    
@login_required
def edit_user_image(request, user_id):
    user = get_object_or_404(User, id=user_id)
    
    # if user.image.file:
    #     # image = get_object_or_404(Image, user_id=user_id)
    #     print(user.image.file)
    #     # image.delete()
    # else:
    #     print('없슈ㅠㅠㅠㅠㅠㅠㅠㅠㅠ')
    images = request.FILES.getlist('file')
    # from IPython import embed; embed()
    if request.method == 'POST':
        for image in images:
            request.FILES['file'] = image
            image_form = ImageForm(files=request.FILES)
            if image_form.is_valid():
                image = image_form.save(commit=False)
                image.user_id = request.user.id
                image.save()
                return redirect('accounts:user_page', user_id)
    else:
        image_form = ImageForm()
    return render(request, 'accounts/image_form.html', {
        'image_form': image_form,
    })

def test(request):
    movies = Movie.objects.all()[:90]
    return render(request, 'accounts/choice.html', {
        'movies':movies
    })

@login_required
def checked(request):
    if request.method == "POST":
        # 어떤 장르 영화를 좋아하는 지
        genre = [0]*28
        checked_list = request.POST.getlist('checked_data')
        print(checked_list)
        user = request.user
        for i in checked_list:
            genre_id, movie_id = i.split(',')
            genre[int(genre_id)] += 1
            movie = get_object_or_404(Movie, id = int(movie_id))
            user.like_movies.add(movie)
        max_point1, max_idd1, max_point2, max_idd2 = 0, 0, 0, 0
        for j in range(28):
            if max_point1 < genre[j]:
                max_point1 = genre[j]
                max_idd1 = j
            else:
                if max_point2 < genre[j]:
                    max_point2 = genre[j]
                    max_idd2 = j
        genre1 = get_object_or_404(Genre, id=max_idd1)
        genre2 = get_object_or_404(Genre, id=max_idd2)
        user.like_genres.add(genre1)
        user.like_genres.add(genre2)
        # 추천 알고리즘
        # genre1_movies = Movie.objects.filter(genre_id=genre1)
        # genre2_movies = Movie.objects.filter(genre_id=genre2)
        # movie = random.choice(genre1_movies)
        # movies1 = random.sample(genre1_movies, 10)
        # movies2 = random.sample(genre2_movies, 10)
        movie = Movie.objects.filter(genre_id=genre1).order_by('-userRating').distinct()[0]
        genre = get_object_or_404(Genre, id=movie.genre_id)
        movies1 = Movie.objects.filter(genre_id=genre1).order_by('-userRating').distinct()[1:10]
        movies2 = Movie.objects.filter(genre_id=genre2).order_by('-userRating').distinct()[:9]

        # 취향 비슷한 사람 찾기
        users = []
        for user1 in User.objects.all():
            genre_li = []
            for like_genre in user1.like_genres.all():
                genre_li.append(like_genre.id)
            if sorted(genre_li) == sorted([max_idd1, max_idd2]) and user1.id != user.id:
                users.append(user1)
        if not users:
            for user2 in User.objects.all():
                if user2.id != user.id:
                    users.append(user2)
                    print(user.id, user2.id)
        return render(request, 'movies/movie_list.html', {
            'movie': movie,
            'genre': genre,
            'movies1' : movies1,
            'movies2' : movies2,
            'users': users,
        })

@login_required
@require_POST
def create_damgle(request, page_master_id):
    page_master = get_object_or_404(User, id=page_master_id)
    damgle_form = DamgleForm(request.POST)
    if damgle_form.is_valid():
        damgle = damgle_form.save(commit=False)
        damgle.user = request.user
        damgle.page_master = page_master
        damgle.save()
    return redirect('accounts:user_page', page_master.id)


@login_required
def delete_damgle(request, page_master_id, damgle_id):
    page_master_id = get_object_or_404(User, id=page_master_id)
    damgle = get_object_or_404(Damgle, page_master_id=page_master_id.id, user_id=request.user.id, id=damgle_id)
    damgle.delete()
    return redirect('accounts:user_page', page_master_id.id)

Django_PJT1/accounts/templates/accounts/choice.html
{% extends 'base.html' %}
{% block body %}
<div style="text-align:center; margin-top:50px;">
<div style="font-size:40px;margin-bottom:0px;">좋아하는 영화를 5개 이상 고르세요.</div>
<div style="font-size:20px;margin-bottom:50px;color:#778899">준비 되었다면 맨 밑에 start</div>
<div style="margin-right:150px;margin-left:150px;">
<form action="{% url 'accounts:checked' %}" method="POST">
    {% csrf_token %}
    {% for movie in movies %}
            {% comment %} <div class="card-body" id="movie{{movie.}}" ></div> {% endcomment %}
            <ul class="title">
                <input type="checkbox" name="checked_data" value="{{ movie.genre_id }}, {{movie.id}}">
                <img src="{{movie.poster_url}}" class="d-block poster" alt="{{ movie.movieName }}-poster">
            </ul>

            {% comment %} <div class="card-body" id="" onclick="">
                <img src="{% movie%}" alt=""> {% endcomment %}
            {% comment %} </div> {% endcomment %}
        
    {% endfor %}
</div>    
    <div><button class="btn btn-secondary" style="width:100%; height:300px; font-size:100px;">Start</button></div>
    </div>

</div>
</form>

<footer class="skicky-bottom">
		<div class="footer-name">
		@2019, Hyun Hee Son and Da Yeon Ha
		</div>
		<div class="right">
			{% comment %} <a href="{% url 'movies:movie_list'%}">NEXT <i class="far fa-hand-point-right fa-3x"></i></a> {% endcomment %}
               <a style="display:scroll;position:fixed;bottom:0px; right:30px;" rel="nofollow"

             href="#scrollbottom" style="font-size:30px;">Go to down<i class="far fa-hand-point-down fa-3x"></i></a>

                <div id="scrollbottom"></div>
		</div>
</footer>


<style>
    img {
        max-width: 100%;
        height: auto !important;
    }

    footer {
    position:sticky;
    bottom:0;
    height: 50px;
    width: 100%;
    padding: 0 3rem;
    color: white;
    background-color: black;
    }


    footer>div {
    display: inline-block;
    }

    footer img {
    width: 50px;
    height: 50px;
    border-radius: 50%;
    }

    .footer-name{
    padding: 10px
    }

    .title {
        width: 230px;
        display: inline-block;
    }

    .right{
    float: right;
    }
</style>
{% endblock %}

Django_PJT1/accounts/templates/accounts/image_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}edit Profile Image 
{% endblock %}

{% block body %}
<div class="container mt-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form image_form %}

        <input class="btn btn-dark" type="submit">
    </form>
</div>
{% endblock %}

Django_PJT1/accounts/templates/accounts/user_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <div class="container mt-5">
        <form method="POST" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark">
        </form>
    </div>
{% endblock %}

Django_PJT1/accounts/templates/accounts/user_page.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<div class="container">
    <div class="row">
        <div class="pr_image col-6" style="display:inline-block; width:300px; text-align:right ">
            <div style="text-align:right">
                {% if user_info.image.file.url %}
                <img src="{{ user_info.image.file.url }}" alt="{{user_info.nickname}}-image" class="rounded-circle"
                    width="300px" height="300px">
                {% else %}
                <!-- 이미지 없으면 기본이미지 사용 -->
                <img src="https://picsum.photos/300/300" alt="random-image" class="rounded-circle" width="300px" height="300px">
                {% endif %}
            </div>
            {% if user == user_info %}
            <a href="{% url 'accounts:edit_user_image' user_info.id %}" class="btn btn-light"
                style="text-align:right">사진 편집</a>
            {% endif %}
        </div>
        <div class="col-6">
            <div>
                <h2 style="display:inline-block;font-size: 50px;">{{user_info.nickname}}</h2>
                <p style="display:inline-block;">({{user_info.username}})</p>
                <!-- 팔로우 버튼, 게시물수, 팔로우 수, 자기소개 등이 들어올 공간 -->
                {% if user == user_info %}
                <a href="{% url 'accounts:edit_user_page' user_info.id %}" class="btn btn-light">프로필 편집</a>
                {% endif %}
            </div>
            <div class="mt-4" style="font-size: 30px;text-align:center;">자기소개</div>
            <p class="ml-5 mr-5" style="font-size: 20px;">{{ user_info.introduction }}</p>
        </div>
    </div>
    <hr style="border: 0.5px solid #DCDCDC;">
    <div>
        <div class="ml-5" style="font-size: 30px; text-align:center;">좋아하는 영화</div>
        {% comment %} {% endcomment %}
        <div class="container">
            <div class="row">
                <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel" data-interval="1000">
                    <div class="MultiCarousel-inner">
                        {% for like_movie in user_info.like_movies.all %}
                        <div class="item">
                            <div class="pad15">
                                <p class="title"><a href="{% url 'movies:movie_detail' like_movie.id%}"><img
                                            src="{{like_movie.poster_url}}" alt="{{like_movie.movieName}}-poster"></a>
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <button class="btn btn-primary leftLst">
                    </button> <button class="btn btn-primary rightLst">
                    </button>
                </div>
            </div>
        </div>
    </div>
        <div class="mb-5" style="font-size: 30px; text-align:center; margin-top:30px;">{{user_info.nickname}}님이 남긴 영화리뷰</div>
            <div class="list-group">
                {% for review in user_info.review_set.all %}
                <a href="{% url 'movies:movie_detail' review.movie_id %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <div class="mb-1" style="font-size:20px;">{{review.movie.movieName}} (평점 : {{review.score}})</div>
                    </div>
                    <p class="mb-1">{{review.content}}</p>
                </a>
                {% endfor %}
            </div>
        

    <div>
        <div class="ml-5 mt-10 mb-4" style="font-size: 30px; text-align:center; margin-top:80px;">담벼락</div>
        <div class="box">

            {% comment %} <div>
                <img src="{{ review.user4[[]] }}" alt="">
            </div> {% endcomment %}
            <div class="mt-5 ml-5 mb-3 mr-5">
    
                {% for damgle in damgles %}
    
                {% if user == damgle.user %}
                    <p class="card-text mt-2 mr-2" style="text-align:right;font-size:20px;"> {{ damgle.content}}<a href="{% url 'accounts:delete_damgle' user_info.id damgle.id %}"><i class="fas fa-eraser fa-1x"></i></a></p>
                {% else %}
                    <p class="card-text mt-2 ml-2" style="text-align:left;font-size:20px;"><a href="{% url 'accounts:user_page' damgle.user.id %}">{{damgle.user}}</a> : {{ damgle.content}}</p>
                {% endif %}
                {% empty %}
                    <p class="card-text" style="text-align:center;">담글이 없습니다.</p>
                {% endfor %}
            </div>
            <div class="card-body">
                <div class="card-footer">
                    <form action="{% url 'accounts:create_damgle' user_info.id %}" method="POST">
                        {% csrf_token %}
                        {% bootstrap_form damgle_form %}
                        {% buttons %}
                        <input type="submit" value="게시" class="btn btn-primary">
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

    <style>
        img {
            max-width: 100%;
            height: auto !important;
        }

        .title {
            width: 200px;
            display: inline-block;
        }

        .MultiCarousel {
            float: left;
            overflow: hidden;
            padding: 15px;
            width: 100%;
            position: relative;
        }

        .MultiCarousel .MultiCarousel-inner {
            transition: 1s ease all;
            float: left;
        }

        .MultiCarousel .MultiCarousel-inner .item {
            float: left;
        }

        .MultiCarousel .MultiCarousel-inner .item>div {
            text-align: center;
            padding: 10px;
            margin: 10px;
            background: #f1f1f1;
            color: #666;
        }

        .MultiCarousel .leftLst,
        .MultiCarousel .rightLst {
            position: absolute;
            border-radius: 50%;
            top: calc(50% - 20px);
        }

        .MultiCarousel .leftLst {
            left: 0;
        }

        .MultiCarousel .rightLst {
            right: 0;
        }

        .MultiCarousel .leftLst.over,
        .MultiCarousel .rightLst.over {
            pointer-events: none;
            background: #ccc;
        }

        .box {
            margin-top: 10px;
            border: 0.5px solid #DCDCDC;
            border-radius: 25px;
        }
    </style>
    <script>
        $(document).ready(function () {
            var itemsMainDiv = ('.MultiCarousel');
            var itemsDiv = ('.MultiCarousel-inner');
            var itemWidth = "";

            $('.leftLst, .rightLst').click(function () {
                var condition = $(this).hasClass("leftLst");
                if (condition)
                    click(0, this);
                else
                    click(1, this)
            });

            ResCarouselSize();




            $(window).resize(function () {
                ResCarouselSize();
            });

            //this function define the size of the items
            function ResCarouselSize() {
                var incno = 0;
                var dataItems = ("data-items");
                var itemClass = ('.item');
                var id = 0;
                var btnParentSb = '';
                var itemsSplit = '';
                var sampwidth = $(itemsMainDiv).width();
                var bodyWidth = $('body').width();
                $(itemsDiv).each(function () {
                    id = id + 1;
                    var itemNumbers = $(this).find(itemClass).length;
                    btnParentSb = $(this).parent().attr(dataItems);
                    itemsSplit = btnParentSb.split(',');
                    $(this).parent().attr("id", "MultiCarousel" + id);


                    if (bodyWidth >= 1200) {
                        incno = itemsSplit[3];
                        itemWidth = sampwidth / incno;
                    } else if (bodyWidth >= 992) {
                        incno = itemsSplit[2];
                        itemWidth = sampwidth / incno;
                    } else if (bodyWidth >= 768) {
                        incno = itemsSplit[1];
                        itemWidth = sampwidth / incno;
                    } else {
                        incno = itemsSplit[0];
                        itemWidth = sampwidth / incno;
                    }
                    $(this).css({
                        'transform': 'translateX(0px)',
                        'width': itemWidth * itemNumbers
                    });
                    $(this).find(itemClass).each(function () {
                        $(this).outerWidth(itemWidth);
                    });

                    $(".leftLst").addClass("over");
                    $(".rightLst").removeClass("over");

                });
            }


            //this function used to move the items
            function ResCarousel(e, el, s) {
                var leftBtn = ('.leftLst');
                var rightBtn = ('.rightLst');
                var translateXval = '';
                var divStyle = $(el + ' ' + itemsDiv).css('transform');
                var values = divStyle.match(/-?[\d\.]+/g);
                var xds = Math.abs(values[4]);
                if (e == 0) {
                    translateXval = parseInt(xds) - parseInt(itemWidth * s);
                    $(el + ' ' + rightBtn).removeClass("over");

                    if (translateXval <= itemWidth / 2) {
                        translateXval = 0;
                        $(el + ' ' + leftBtn).addClass("over");
                    }
                } else if (e == 1) {
                    var itemsCondition = $(el).find(itemsDiv).width() - $(el).width();
                    translateXval = parseInt(xds) + parseInt(itemWidth * s);
                    $(el + ' ' + leftBtn).removeClass("over");

                    if (translateXval >= itemsCondition - itemWidth / 2) {
                        translateXval = itemsCondition;
                        $(el + ' ' + rightBtn).addClass("over");
                    }
                }
                $(el + ' ' + itemsDiv).css('transform', 'translateX(' + -translateXval + 'px)');
            }

            //It is used to get some elements from btn
            function click(ell, ee) {
                var Parent = "#" + $(ee).parent().attr("id");
                var slide = $(Parent).attr("data-slide");
                ResCarousel(ell, Parent, slide);
            }

        });
    </script>
    {% endblock %}