Django_PJT1/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('test/', views.test, name='test'),
    path('checked/', views.checked, name='checked'),

    path('user_page/<int:user_id>/', views.user_page, name='user_page'),
    path('user_page/<int:user_id>/edit/', views.edit_user_page, name='edit_user_page'),

    path('user_page/<int:user_id>/edit_image/', views.edit_user_image, name='edit_user_image'),
    path('user_page/<int:page_master_id>/damgle/create/', views.create_damgle, name='create_damgle'),
    path('user_page/<int:page_master_id>/damgle/<int:damgle_id>/delete', views.delete_damgle, name='delete_damgle'),
]

Django_PJT1/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('search_movie/', views.search_movie, name='search_movie'),
    path('<int:movie_id>/like/', views.toggle_like, name='like'),
    path('<int:movie_id>/reviews/create/', views.create_review, name='create_review'),
    # path('<int:movie_id>/reviews/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('<int:movie_id>/reviews/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

Django_PJT1/test_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
import movies
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', movies.views.index),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_PJT1/movies/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
# User = get_user_model()
User = settings.AUTH_USER_MODEL

class Genre(models.Model):
    name = models.CharField(max_length=20)
    
class Movie(models.Model):
    MovieCd = models.IntegerField()
    movieName = models.CharField(max_length=30)
    movieNameE = models.CharField(max_length=30)
    pubDate = models.IntegerField()
    runtime = models.CharField(max_length=200)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='movie_genre') # 여기가 변경사항
    director = models.CharField(max_length=200)
    userRating = models.FloatField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    like_users = models.ManyToManyField(User, related_name='like_movies')
    
class Review(models.Model):
    content = models.CharField(max_length=150)
    score = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

Django_PJT1/movies/forms.py
from django import forms
from .models import Movie, Genre, Review

class ReviewForm(forms.ModelForm):
    content = forms.CharField(max_length=500)
    score = forms.IntegerField(max_value=5, min_value=1)
    class Meta:
        model = Review
        fields = ('content', 'score', )

Django_PJT1/movies/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import Movie, Genre, Review
from .forms import ReviewForm
import random
User = get_user_model()

def index(request):
    return render(request, 'movies/index.html')


# Create your views here.
@login_required
def movie_list(request):
    user = request.user
    genres = user.like_genres.all()
    li = []
    users = []
    for genre in genres:
        li.append(genre.id)
    genre1_movies = Movie.objects.filter(genre_id=li[0])
    genre2_movies = Movie.objects.filter(genre_id=li[1])
    movie = random.choice(genre1_movies)
    genre = get_object_or_404(Genre, id=movie.genre_id)
    # print('----------------------')
    # print(movie.movieName, type(genre1_movies))
    genre1 = []
    genre2 = []
    for genre11 in genre1_movies:
        genre1.append(genre11)
    for genre22 in genre2_movies:
        genre2.append(genre22)
    if len(genre1) > 9:
        movies1 = random.sample(genre1, 9)
    else:
        movies1 = random.shuffle(genre1)
    if len(genre2) > 9:
        movies2 = random.sample(genre2, 9)
    else:
        movies2 = random.shuffle(genre2)
    # movies1 = Movie.objects.filter(genre_id=li[0]).order_by('-userRating').distinct()[1:10]
    # movies2 = Movie.objects.filter(genre_id=li[1]).order_by('-userRating').distinct()[:9]

    for user1 in User.objects.all():
        genre_li = []
        for like_genre in user1.like_genres.all():
            genre_li.append(like_genre.id)
        if sorted(genre_li) == sorted(li) and user1.id != user.id:
            users.append(user1)
    if not users:
        users = User.objects.all()
    return render(request, 'movies/movie_list.html', {
        'movie' : movie,
        'genre' : genre,
        'movies1': movies1,
        'movies2': movies2,
        'users':users
    })

@login_required
def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    genre = get_object_or_404(Genre, id=movie.genre_id)
    is_like = movie.like_users.filter(id=request.user.id).exists()
    review_form = ReviewForm()
    # review_form = ReviewForm()
    # is_like = movie.like_users.filter(id=request.user.id).exists()
    
    return render(request, 'movies/movie_detail.html', {
        'movie': movie,
        'genre': genre,
        'review_form': review_form,
        'is_like': is_like,
        
    })

@login_required
def search_movie(request):
    search_movie = request.GET.get('search_movie')
    # print(search_movie)
    search_movies = Movie.objects.filter(movieName__contains=search_movie).distinct()
    # print(search_movies)
    return render(request, 'movies/search_movie.html', {'search_movies': search_movies})
        
@login_required
@require_POST
def toggle_like(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    user = request.user
    # 좋아요를 누른 유저라면
    if movie.like_users.filter(id=user.id).exists():
        movie.like_users.remove(user)
    else:
        movie.like_users.add(user)
    genre = [0]*28
    for user_movie in user.like_movies.all():
        genre[user_movie.genre_id] += 1
    max_point1, max_idd1, max_point2, max_idd2 = 0, 0, 0, 0
    for j in range(28):
        if max_point1 < genre[j]:
            max_point1 = genre[j]
            max_idd1 = j
        else:
            if max_point2 < genre[j]:
                max_point2 = genre[j]
                max_idd2 = j
    for i in user.like_genres.all():
        user.like_genres.remove(i)
    genre1 = get_object_or_404(Genre, id=max_idd1)
    genre2 = get_object_or_404(Genre, id=max_idd2)
    user.like_genres.add(genre1)
    user.like_genres.add(genre2)
    return redirect('movies:movie_detail', movie.id)

@login_required
@require_POST
def create_review(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        review.user = request.user
        review.movie = movie
        review.save()
    return redirect('movies:movie_detail', movie.id)

@login_required
def delete_review(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, movie_id=movie.id, id=review_id)
    if review.user == request.user:
        review.delete()
    return redirect('movies:movie_detail', movie.id)

# def edit_review(request, movie_id, review_id):
#     movie = get_object_or_404(Movie, id=movie_id)
#     review = get_object_or_404(Review, movie_id=movie.id, id=review_id)
#     if request.method == 'POST':    
#         review_form = ReviewForm(request.POST, instance=review)
#         if review_form.is_valid():
#             review=review_form.save()
#             return redirect('movies:movie_detail', movie.id)

#     else:
#         review_form = ReviewForm(instance=review)
#     return render(request, 'movies/review_form.html', {
#         'review_form':review_form
#     })

Django_PJT1/movies/templates/movies/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Gaegu|Gugi|Jua&display=swap&subset=korean" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Gugi&display=swap&subset=korean" rel="stylesheet">

    <title>Index page</title>
    <style>
    body {
        background-image: url('{% static '/images/background1.jpg' %}');
    }
    div {
        font-family: 'Jua', sans-serif;
        color:white;
        text-align:center;
    }
    .title {
        margin-top: 240px;
        margin-bottom: 20px;
        font-size: 50px;
    }

    .custom {
    width: 90px !important;
    }
    
    </style>
</head>
<body>
    <div class="background">
        <div class="title"> Recommend movies by sonyeonhada
        </div>
        <div class="discription">
        나의 취향을 기반으로 영화를 추천받는 사이트입니다.<br>영화를 추천 받고 나와 취향이 같은 사람들과 영화에 대해 이야기하시겠습니까?
        </div>
        <a href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-outline-light mt-3 btn-lg custom">Signup</button></a>
        <a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-outline-light mt-3 btn-lg ml-2 custom">Login</button></a>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Django_PJT1/movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}
<div class="container mt-5">

    <div class="row">
        <div class="col-6">
            <div class="title">
                <img src="{{movie.poster_url}}" class="h-70 poster" alt="{{ movie.movieName }}-poster">
            </div>
        </div>
        <div class="col-6">
            <div class="list-gruop mt-5">
                <div class="moviename">{{movie.movieName}} ({{movie.movieNameE}})</div>
                <form action="{% url 'movies:like' movie.id %}" method="POST" style="display:inline-block">
                    {% csrf_token %}
                    <button style="border:0; background:none;">

                        <i 
                        class="{% if is_like %}fas{% else %}far{% endif %}
                            fa-heart fa-4x js-like-button"
                        data-id="{{ movie.id }}"
                        style="color:crimson;">
                        
                        </i>
                    </button>
                </form>
                <li class="list-item" style="margin-top:0px;">평점 : <div class="userrating">{{movie.userRating}}</div>
                </li>
                <li class="list-item">장르 : {{genre.name}}</li>
                <li class="list-item">감독 : {{movie.director}}</li>
                <li class="list-item">개봉일 : {{movie.pubDate}}</li>
                <li class="list-item">줄거리</li>
                <div class="description">{{movie.description}}</div>
            </div>
        </div>
    </div>
    {% comment %} 리뷰 {% endcomment %}
    <div class="mt-5 mb-5" style="font-size: 50px;text-align: center;">Reviews</div>
    <div class="box">
        
        {% comment %} <div>
            <img src="{{ review.user4[[]] }}" alt="">
        </div> {% endcomment %}
            <div class="mt-5 ml-5 mb-3">
        {% for review in movie.review_set.all %}
            <div class="row">
            <div class="col-10">
            <p class="card-text mt-2 ml-2" style="text-align:left;font-size:20px;"><a href="{% url 'accounts:user_page' review.user.id %}">{{review.user}}</a> : (평점 : {{ review.score }}) {{review.content}}</p>
            </div>
            {% if  user == review.user %}
            <div class="col-1">
            <form href="#"><i class="far fa-edit fa-2x"></i></form>
            </div>
            <div class="col-0.5">
            <a href="{% url 'movies:delete_review' movie.id review.id %}"><i class="fas fa-eraser fa-2x"></i></a>
            </div>
            {% endif %}
            </div>
        {% empty %}
        <p class="card-text" style="text-align:center;">댓글이 없습니다.</p>
        {% endfor %}
        </div>
        <div class="card-body">
            <div class="card-footer">
                {% load bootstrap4 %}
                <form action="{% url 'movies:create_review' movie.id %}"method="POST">
                    {% csrf_token %}
                    {% bootstrap_form review_form %}
                        {% buttons %}
                    <input type="submit" value="게시" class="btn btn-primary">
                        {% endbuttons %}
                </form>
            </div>
        </div>

        <style>
            img {
                max-width: 100%;
                height: auto !important;

            }

            .moviename {
                font-size: 50px;
                display: inline-block;
            }

            .userrating {
                color: white;
                background: blue;
                display: inline-block;
            }

            .description {
                word-break: break-all;
                line-height: 25px;
            }

            .title {
                width: 500px;
                display: inline-block;
            }

            .box {
                margin-top: 10px;
                border: 0.5px solid #DCDCDC;
                border-radius: 25px;
            }
        </style>

        <script>
        const likeButtons = document.querySelectorAll('.js-like-button');

        likeButtons.forEach((likeButton) => {
            likeButton.addEventListener('click', function (event) {
                const URL = `/movies/${event.target.dataset.id}/like/`;
                axios.defaults.xsrfCookieName = 'csrftoken';
                axios.defaults.xsrfHeaderName = 'X-CSRFToken';
                axios.post(URL)
                    .then((res) => {
                        if (res.data.liked) { // 지금 좋아요가 끝난거면
                            event.target.classList.remove('far');
                            event.target.classList.add('fas');
                        }
                        else { // 지금 좋아요를 해제했다면
                            event.target.classList.remove('fas');
                            event.target.classList.add('far');
                        }
                    })
            });
        });

        
        
        </script>
        {% endblock body %}

Django_PJT1/movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% block title %}Movie list
{% endblock %}

{% block body %}
{% comment %} <a href="{% url 'cinema:new_movie' %}">
    <button>Add New Movie</button>
</a> {% endcomment %}
<header class="header-title">
    <h2 class="header-title-h">오늘은 {{genre.name}} 영화 한 편 어떠세요?</h2>
    <div class="row">
        <div class="col-6 right">
            <div class="center">
                <div class="title">
                    <img src="{{movie.poster_url}}" class="h-70 poster" alt="{{ movie.movieName }}-poster">
                </div>
                <div class="moviename">{{movie.movieName}} ({{movie.movieNameE}})</div>
            </div>
        </div>
        <div class="col-6 white">
            <div class="list-gruop">
                <li class="list-item">평점 : <div class="userrating">{{movie.userRating}}</div>
                </li>
                <li class="list-item">장르 : {{genre.name}}</li>
                <li class="list-item">감독 : {{movie.director}}</li>
                <li class="list-item">개봉일 : {{movie.pubDate}}</li>
                <li class="list-item">줄거리 : </li>
                <div class="description" style="display:inline-block">{{movie.description}}</div>
                <li class="list-item" style="display:inline-block; margin-top:0px;">...... </li>
                <a href="{% url 'movies:movie_detail' movie.id%}">더보기</a>
            </div>
        </div>
    </div>

</header>
<div class="row">
    <div class="col-8">
        <div class="col-11 body-center box">
            <div class="recommenduser"  style="margin-top:20px;">당신을 위한 추천 list</div>
            <div class="card-columns">
                {% for movie1 in movies1 %}
                <div class="card my-3 mb-3">
                    <a href="{% url 'movies:movie_detail' movie1.id %}">
                        <img src="{{movie1.poster_url}}" class="h-10 poster" alt="{{ movie1.movieName }}-poster">
                    </a>
                </div>
                {% endfor %}
                {% for movie2 in movies2 %}
                <div class="card my-3">
                    <a href="{% url 'movies:movie_detail' movie2.id %}">
                        <img src="{{movie2.poster_url}}" class="card-img-top d-block w-100 poster"
                            alt="{{ movie2.movieName }}-poster">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-3 box">
        <div class="recommenduser mb-4" style="margin-top:20px;">취향 저격 User</div>
        <div class="list-group">
            {% for user in users %}

            <a href="{% url 'accounts:user_page' user.id %}" class="list-group-item list-group-item-action">
                {{ user.username }}
            </a>
            {% endfor %}
        </div>
    </div>
</div>
<style>
    header {
        float: top;
        padding-top: 0px;
        margin-top: 0px;
        height: 700px;
        width: 100%;
        background: #000;
        line-height: 40px;
    }

    img {
        max-width: 100%;
        height: auto !important;
    }

    .title {
        width: 300px;
        display: inline-block;
    }

    .body-center {
        float: right;
        text-align: center;
    }

    .userrating {
        margin-top: 80px;
        color: white;
        background: blue;
        display: inline-block;
    }

    .description {
        word-break: break-all;
        display: inline-block;
        width: 500px;
        height: 270px;
        overflow: hidden;
        text-overflow: ellipsis;
        line-height: 25px;
        padding-bottom: 0px;
        margin-bottom: 0px;
    }

    .center {
        padding-top: 25px;
        width: 500px;;
        display: inline-block;
        text-align: center;
    }

    .header-title-h {
        padding-top: 25px;
        text-align: center;
        font-size: 30px;
        color: #FFFFFF;
    }

    .right {
        padding-top: 25px;
        text-align: right;
        font-size: 25px;
        color: #FFFFFF;
    }

    .moviename {
        padding-top: 25px;
        font-size: 25px;
        color: #FFFFFF;
    }

    .box {
        margin-top: 10px;
        border: 0.5px solid #DCDCDC;
        border-radius: 25px;
    }

    .recommenduser {
        margin-top: 10px;
        margin-bottom: 10px;
        font-size: 50px;
        text-align: center;
    }
</style>
{% endblock %}

Django_PJT1/movies/templates/movies/review_form.html
{% load bootstrap4 %}
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form review_form %}
        {% buttons %}
    <input type="submit" value="게시" class="btn btn-primary">
        {% endbuttons %}
</form>

Django_PJT1/movies/templates/movies/search_movie.html
{% extends 'base.html' %}
{% block body %}

    {% if search_movies %}
    <div class="card-columns container">
    {% for search_movie in search_movies %}
        <div class="card my-3 mb-3">
            <a href="{% url 'movies:movie_detail' search_movie.id %}">
                <img src="{{search_movie.poster_url}}" class="d-block w-100 poster" alt="{{ search_movie.movieName }}-poster">
        </div>
    {% endfor %}
    </div>
    {% endif %}
{% endblock  %}