Django_PJT1/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('test/', views.test, name='test'),
    path('checked/', views.checked, name='checked'),

    path('user_page/<int:user_id>/', views.user_page, name='user_page'),
    path('user_page/<int:user_id>/edit/', views.edit_user_page, name='edit_user_page'),

    path('user_page/<int:user_id>/edit_image/', views.edit_user_image, name='edit_user_image'),
    path('user_page/<int:page_master_id>/damgle/create/', views.create_damgle, name='create_damgle'),
    path('user_page/<int:page_master_id>/damgle/<int:damgle_id>/delete', views.delete_damgle, name='delete_damgle'),
]

Django_PJT1/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('search_movie/', views.search_movie, name='search_movie'),
    path('<int:movie_id>/like/', views.toggle_like, name='like'),
    path('<int:movie_id>/reviews/create/', views.create_review, name='create_review'),
    # path('<int:movie_id>/reviews/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('<int:movie_id>/reviews/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

Django_PJT1/test_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
import movies
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', movies.views.index),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_PJT1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Gaegu|Gugi|Jua&display=swap&subset=korean" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Gugi&display=swap&subset=korean" rel="stylesheet">


    <title>{% block title %}{% endblock title %}</title>
    <script src="https://kit.fontawesome.com/84a0eb3116.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light black px-5">
        <a class="navbar-brand white" style="color:white;" href="{% url 'movies:movie_list' %}">
            <i class="far fa-camera-movie fa-inverse"></i> | Recommend movies by sonyeonhada
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link white" style="color:white;" href="{% url 'accounts:user_page' user.id %}">MyPage</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link white" style="color:white;" href="{% url 'accounts:logout'%}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link white" style="color:white;" href="{% url 'accounts:signup'%}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link white" style="color:white;" href="{% url 'accounts:login'%}">Login</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <form class="nav-link" action="{% url 'movies:search_movie'%}" method="GET">
                        <input type="text" name="search_movie">
                        {% comment %} 나중에 javascript로 얘로 바꾸자 <i class="far fa-search"></i> {% endcomment %}
                        <input type="submit" value="search">
                    </form>
                </li>
            </ul>
        </div>
    </nav>
    {% block body %}{% endblock body %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <style>
    body {
        font-family: 'Jua', sans-serif;
    }
    
    .white {
        color:white;
    }

    .black {
        background-color: black;
    }

    <style>
<body>
</html>